const $=s=>document.querySelector(s); let db=[];
const norm=v=>String(v??'').toUpperCase().replace(/[^A-ZÆØÅ0-9]/g,'');
function save(){localStorage.setItem('parkingDb',JSON.stringify(db));renderStatus()}
function renderStatus(){$('#count').textContent=`${db.length} registreringsnummer`;$('#status').textContent=db.length?`Liste klar • ${db.length} biler`:'Ingen liste importert'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lookup(){const raw=$('#q').value,q=norm(raw),box=$('#result');if(!q){box.className='result idle';box.innerHTML='<strong>Klar for oppslag</strong><span>Skann eller skriv inn et bilnummer.</span>';return}const hits=db.filter(x=>x.reg===q);if(hits.length){box.className='result ok';box.innerHTML=`<strong>✓ GODKJENT</strong><span>${esc(formatReg(q))} • ${hits.map(x=>esc(x.name)).join(', ')}</span>`}else{box.className='result no';box.innerHTML=`<strong>✕ IKKE FUNNET</strong><span>${esc(formatReg(q))}</span>`}}
function formatReg(r){return r.length>2?r.slice(0,2)+' '+r.slice(2):r}
$('#q').addEventListener('input',lookup);$('#clear').onclick=()=>{$('#q').value='';lookup();$('#q').focus()};
$('#forget').onclick=()=>{if(confirm('Slette den lokalt lagrede parkeringslisten?')){db=[];localStorage.removeItem('parkingDb');renderStatus();lookup()}};
$('#file').addEventListener('change',async e=>{try{if(!e.target.files[0])return;const data=await e.target.files[0].arrayBuffer(),wb=XLSX.read(data),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)throw Error('Arket er tomt');const keys=Object.keys(rows[0]),nk=keys.find(k=>norm(k)==='NAVN'),rk=keys.find(k=>['REGISTRERINGSNUMMER','BILNUMMER','REGNR','SKILT'].includes(norm(k)));if(!nk||!rk)throw Error('Fant ikke kolonnene Navn og Registreringsnummer');db=rows.map(r=>({name:String(r[nk]).trim(),reg:norm(r[rk])})).filter(x=>x.reg);save();$('#q').value='';lookup();alert(`Importerte ${db.length} registreringsnummer.`)}catch(err){alert('Kunne ikke importere: '+err.message)}finally{e.target.value=''}});
function candidates(text){const compact=String(text).toUpperCase().replace(/[^A-Z0-9ÆØÅ\n ]/g,' ');const found=[];for(const line of compact.split(/\n/)){const s=norm(line);for(const m of s.matchAll(/[A-ZÆØÅ]{2}[0-9]{4,5}/g))found.push(m[0])}for(const m of norm(compact).matchAll(/[A-ZÆØÅ]{2}[0-9]{4,5}/g))found.push(m[0]);return [...new Set(found)]}
function bestCandidate(list){if(!list.length)return null;const exact=list.find(c=>db.some(x=>x.reg===c));return exact||list[0]}
$('#camera').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const st=$('#scanStatus'),preview=$('#preview');st.hidden=false;st.textContent='Forbereder bilde…';preview.src=URL.createObjectURL(file);preview.hidden=false;try{if(!window.Tesseract)throw Error('OCR-biblioteket kunne ikke lastes. Kontroller internettilkoblingen.');st.textContent='Leser skilt… første gang kan ta litt tid.';const result=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')st.textContent=`Leser skilt… ${Math.round((m.progress||0)*100)} %`}});const list=candidates(result.data.text),best=bestCandidate(list);if(!best){st.textContent='Fant ikke et tydelig registreringsnummer. Prøv et nærmere og rettere bilde.';return}$('#q').value=formatReg(best);lookup();st.textContent=`Leste: ${formatReg(best)}`;$('#result').scrollIntoView({behavior:'smooth',block:'center'})}catch(err){st.textContent='Kunne ikke lese bildet: '+err.message}finally{e.target.value=''}});
try{db=JSON.parse(localStorage.getItem('parkingDb')||'[]')}catch{}renderStatus();lookup();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js');
