const $=s=>document.querySelector(s); let db=[],stream=null,scanning=false,ocrBusy=false,scanTimer=null;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-ZÆØÅ0-9]/g,'');
function save(){localStorage.setItem('parkingDb',JSON.stringify(db));renderStatus()}
function renderStatus(){$('#count').textContent=`${db.length} registreringsnummer`;$('#status').textContent=db.length?`Liste klar • ${db.length} biler`:'Ingen liste importert'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatReg(r){r=norm(r);return r.length>2?r.slice(0,2)+' '+r.slice(2):r}
function validNorwegian(r){return /^[A-ZÆØÅ]{2}[0-9]{5}$/.test(norm(r))}
function lookup(){const q=norm($('#q').value),box=$('#result');if(!q){box.className='result idle';box.innerHTML='<strong>Klar for oppslag</strong><span>Skann eller skriv inn et bilnummer.</span>';return}if(!validNorwegian(q)){box.className='result wait';const need=Math.max(0,7-q.length);box.innerHTML=`<strong>Venter på komplett skilt</strong><span>${esc(formatReg(q))}${need?' • mangler '+need+' tegn':''}</span>`;return}const hits=db.filter(x=>x.reg===q);if(hits.length){box.className='result ok';box.innerHTML=`<strong>✓ GODKJENT</strong><span>${esc(formatReg(q))} • ${hits.map(x=>esc(x.name)).join(', ')}</span>`}else{box.className='result no';box.innerHTML=`<strong>✕ IKKE FUNNET</strong><span>${esc(formatReg(q))}</span>`}}
$('#q').addEventListener('input',lookup);$('#clear').onclick=()=>{$('#q').value='';lookup();$('#q').focus()};
$('#forget').onclick=()=>{if(confirm('Slette den lokalt lagrede parkeringslisten?')){db=[];localStorage.removeItem('parkingDb');renderStatus();lookup()}};
$('#file').addEventListener('change',async e=>{try{if(!e.target.files[0])return;const data=await e.target.files[0].arrayBuffer(),wb=XLSX.read(data),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)throw Error('Arket er tomt');const keys=Object.keys(rows[0]),nk=keys.find(k=>norm(k)==='NAVN'),rk=keys.find(k=>['REGISTRERINGSNUMMER','BILNUMMER','REGNR','SKILT'].includes(norm(k)));if(!nk||!rk)throw Error('Fant ikke kolonnene Navn og Registreringsnummer');db=rows.map(r=>({name:String(r[nk]).trim(),reg:norm(r[rk])})).filter(x=>x.reg);save();$('#q').value='';lookup();alert(`Importerte ${db.length} registreringsnummer.`)}catch(err){alert('Kunne ikke importere: '+err.message)}finally{e.target.value=''}});

function extractCandidates(text){const clean=String(text).toUpperCase().replace(/[^A-ZÆØÅ0-9\n ]/g,' '),out=[];for(const line of clean.split(/\n/)){const s=norm(line);for(const m of s.matchAll(/[A-ZÆØÅ]{2}[0-9]{5}/g))out.push(m[0])}for(const m of norm(clean).matchAll(/[A-ZÆØÅ]{2}[0-9]{5}/g))out.push(m[0]);return [...new Set(out)]}
function partialCandidate(text){const clean=String(text).toUpperCase().replace(/[^A-ZÆØÅ0-9]/g,'');const m=clean.match(/[A-ZÆØÅ]{2}[0-9]{1,5}/);return m?m[0]:null}
function setScanStatus(t){const s=$('#scanStatus');s.hidden=false;s.textContent=t}
function preprocessFromVideo(){const v=$('#video'),c=$('#crop');if(!v.videoWidth)return null;const vw=v.videoWidth,vh=v.videoHeight;const cropW=Math.round(vw*.82),cropH=Math.round(cropW*.23),sx=Math.round((vw-cropW)/2),sy=Math.round((vh-cropH)/2);c.width=cropW*2;c.height=cropH*2;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,sx,sy,cropW,cropH,0,0,c.width,c.height);const im=x.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=.299*d[i]+.587*d[i+1]+.114*d[i+2];const val=g>145?255:0;d[i]=d[i+1]=d[i+2]=val}x.putImageData(im,0,0);return c}
async function recognizeCanvas(canvas){const r=await Tesseract.recognize(canvas,'eng',{logger:m=>{if(m.status==='recognizing text'&&scanning)setScanStatus(`Leser skilt… ${Math.round((m.progress||0)*100)} %`)}});return r.data.text}
async function scanFrame(){if(!scanning||ocrBusy)return;ocrBusy=true;try{const c=preprocessFromVideo();if(!c)return;const text=await recognizeCanvas(c),full=extractCandidates(text)[0],partial=partialCandidate(text);if(full){$('#q').value=formatReg(full);lookup();setScanStatus(`Leste: ${formatReg(full)}`);if(validNorwegian(full)){stopCamera();$('#result').scrollIntoView({behavior:'smooth',block:'center'});return}}else if(partial){$('#q').value=formatReg(partial);lookup();setScanStatus(`Ser: ${formatReg(partial)} • fortsetter å skanne…`)}else setScanStatus('Leter etter 2 bokstaver + 5 sifre…')}catch(e){setScanStatus('OCR-feil: '+e.message)}finally{ocrBusy=false;if(scanning)scanTimer=setTimeout(scanFrame,700)}}
async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Nettleseren gir ikke tilgang til live-kamera.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});const v=$('#video');v.srcObject=stream;await v.play();$('#liveWrap').hidden=false;$('#liveControls').hidden=false;$('#liveBtn').hidden=true;scanning=true;setScanStatus('Kamera klart • plasser skiltet i rammen');setTimeout(scanFrame,500)}catch(e){setScanStatus('Kunne ikke starte kamera: '+e.message)}}
function stopCamera(){scanning=false;clearTimeout(scanTimer);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#video').srcObject=null;$('#liveWrap').hidden=true;$('#liveControls').hidden=true;$('#liveBtn').hidden=false}
$('#liveBtn').onclick=startCamera;$('#stopBtn').onclick=stopCamera;document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream)stopCamera()});

$('#camera').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const preview=$('#preview');preview.src=URL.createObjectURL(file);preview.hidden=false;try{setScanStatus('Leser bilde…');const r=await Tesseract.recognize(file,'eng'),full=extractCandidates(r.data.text)[0],partial=partialCandidate(r.data.text);const got=full||partial;if(!got){setScanStatus('Fant ikke et registreringsnummer. Prøv et nærmere bilde.');return}$('#q').value=formatReg(got);lookup();setScanStatus(full?`Leste: ${formatReg(full)}`:`Leste bare: ${formatReg(partial)} • kompletter manuelt.`)}catch(err){setScanStatus('Kunne ikke lese bildet: '+err.message)}finally{e.target.value=''}});
try{db=JSON.parse(localStorage.getItem('parkingDb')||'[]')}catch{}renderStatus();lookup();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js');
